### ISSUE TITLE
Add option to transform URLs into hyperlinks

### ISSUE THREAD

**Issue by bondjimbond** [bondjimbond/islandora_metadata_extras#16]
Metadata displays do not by default automatically present URLs as hyperlinks. They typically appear in plaintext. It would be useful to have the option to have IME scan the Solr fields being presented for display, identify any obvious URLs (http, https), and if there are no anchor tags around the URL already, add them.

**Comment by mjordan** [comment]
Hi @bondjimbond, does this post by @adam-vessey cover what you want to happen?

https://groups.google.com/d/msg/islandora/-Zg4Uo3bSHs/UOco4ZvkDAAJ

**Comment by bondjimbond** [comment]
Thanks, @mjordan. Went to the config page, and I do have it enabled. Weird thing is, it seems to be working - but only sometimes.

I tried creating a fresh object with a URL in the useAndReproduction field, got plaintext. Created a little JS file in Islandora Metadata Extras and called on it, and the URLs started working. Then I turned off the setting, and the URLs continue to work. So I don't know why it was plaintext initially.

**Comment by mjordan** [comment]
> Then I turned off the setting

Are you referring to the "islandora_solr_metadata_filtered_html" setting? I'm not sure, but caching might be in play there, if you're viewing as anonymous.

Your JS would form the basis of a great new feature, but I'd like to make sure that the "islandora_solr_metadata_filtered_html" works as intended before we go any further. We'd need to make sure we didn't double-URLify any links too.

**Comment by bondjimbond** [comment]
Naw, I meant I turned off my custom JS thing. Going back to stock Islandora Metadata Extras.

Having gone back to the stock module, links still display. Turning off the URL encoding feature in the text filter presents URLs in plaintext. Turning it back on, the results give clickable links again.

So there was some kind of fluke that caused my URLs to be presented in plaintext initially -- I don't know why, but that ended. So... since there's no way to test this for now, I'll probably just close this issue..

**Comment by mjordan** [comment]
OK, go ahead and close for now and if we want to reopen later for some reason we can.
