### ISSUE TITLE
Map and modify facet labels for a given Solr field

### ISSUE THREAD

**Issue by bondjimbond** [bondjimbond/islandora_metadata_extras#20]
As I'm doing more with Rights Statements (rightsstatements.org) and Creative Commons licenses, I would love to be able to facet on these in search results.

Since these fields contain URIs, displaying the URI in the facets section is not super helpful. It would be nice to map the URI to a label, and use that in the facet block.

I'm imagining a repeatable fieldset, much like the "Name" fieldset in the stock ingest forms, where you can add multiple sets of mappings and specify:

1. Solr field to affect
2. Field content | Custom label for that content (much like in the namespace rewriting feature I added before)

Does this seem plausible/desirable?

**Comment by bondjimbond** [comment]
This could be done by  modifying the Rewrite Namespace function to become multivalued... basically, put the Solr Field and the Replacement Patterns field in a repeatable fieldset. I'll look into the method for doing this, but if you've got ideas please let me know.

**Comment by bondjimbond** [comment]
Maybe not quite a straight replacement, it looks like: I think the namespace thing is slightly more complex. But a new fieldset for a straight content replacement should work.

**Comment by bondjimbond** [comment]
Difficulty in finding a hook to alter the display content of the facet. Any suggestions?

**Comment by mjordan** [comment]
Best I can suggest is overriding https://github.com/Islandora/islandora_solr_search/blob/7.x/theme/theme.inc#L114.
