### ISSUE TITLE
Edit Metadata tab goes to MODS by default and not selected datastream - bug

### ISSUE THREAD

**Issue by dmoses** [bondjimbond/islandora_metadata_extras#26]
When the option _Display tab containing direct link to edit an object's metadata._ is selected and PBCORE is set as the metadata DSID, it tries to load the link edit_metadata (which tries to load MODS) instead of the edit path to the datastream configured.

**Comment by mjordan** [comment]
@dmoses can you `git pull` in the 7.x branch and try again?

**Comment by dmoses** [comment]
Tested that Mark and now works as expected.
Thanks.

**Comment by mjordan** [comment]
Great, sorry about that, poor testing on my part. I'm glad you found this module!

**Comment by mjordan** [comment]
Resolved with 863fe74cea3774a72b4ed88e9c1325d48c37788b.
