### ISSUE TITLE
Namespace Replacements should only happen on exact matches

### ISSUE THREAD

**Issue by bondjimbond** [bondjimbond/islandora_metadata_extras#30]
Just discovered a weird issue with the Namespace Replacements section. It's accepting partial matches and doing some weird stuff to replace them.

For example: I have the following set up in my Namespace Replacements field..

```
ir|Scholar
irbu|Brandon University
```

If an object with the `irbu` namespace shows in my search results, the field rewrites it to "Scholarbu" -- because it first saw "ir", plugged in the replacement, and then added the rest of the namespace to the result.

We need this to trigger only on exact matches so that this kind of error doesn't occur.

**Comment by mjordan** [comment]
Quick look, without testing, suggests that the regex at https://github.com/mjordan/islandora_metadata_extras/blob/7.x/includes/utilities.inc#L49 is too permissive. Got time to put together a PR?

**Comment by bondjimbond** [comment]
Not today, but hopefully next week..

**Comment by mjordan** [comment]
Cool, I can test.

**Comment by bondjimbond** [comment]
PR in! Pretty simple fix, really. Looking back, I'm not sure why we went with regex instead of a straight up `if ($namespace == $string)` statement in the first place.

**Comment by mjordan** [comment]
Works as advertised. Thanks for finding this.
