### ISSUE TITLE
Allow facet replacement for multiple Solr fields

### ISSUE THREAD

**Issue by bondjimbond** [bondjimbond/islandora_metadata_extras#33]
Now that #20 has been handled... How can we make this functionality work for more than one Solr field?

e.g. I want to replace values in mods_accessCondition_use_and_reproduction_ms, but I ALSO want to replace them in PID_namespace_ss.

Thinking:

- Admin form needs to allow multiple iterations of the namespace field and replacement field... This is doable in the ingest forms, but is there a simple way to do the same thing in Drupal forms?
- The function would have to associate the iterations appropriately (don't want to accidentally do replacements in replacement_field_2 on solr_field_1).

**Comment by mjordan** [comment]
One definition per line won't work?, e.g., 

```
mods_accessCondition_use_and_reproduction_ms|Access Condition
PID_namespace_ss|Namespace
```

**Comment by bondjimbond** [comment]
Not sure if I'm communicating this clearly...

Present implementation:
- Two form fields: Solr field to modify (single text entry), and values to change (multi-line piped entries)
- Allows you to choose one Solr field, and modify an arbitrary selection of values that it might contain.

Desired implementation:
- Multiple iterations of the above two form fields, so that you can choose more than one Solr field, and specify a set of values to modify for each Solr field you specify.

**Comment by mjordan** [comment]
Sorry. I think I know what you mean now - you want to be able to add additional pairs of fields using an "Add" button like this:

![image](https://user-images.githubusercontent.com/403918/73287449-23441200-41ae-11ea-9ba8-0401def9eac0.png)
 
Is that it?

**Comment by bondjimbond** [comment]
Yes, pretty much. Trick is that each Solr field has to be matched only with its particular replacement pair field, and not with the others.

**Comment by mjordan** [comment]
I've never dealt with bound pairs of fields (or "Add" logic), but I've seen them. Maybe if you can find an example from some other module of what you're looking for, we can reverse engineer it.

**Comment by bondjimbond** [comment]
I've seen it in XML Forms, but I don't think that's applicable here. Not really finding it in other modules. Any ideas where you might have seen such a thing?
