### ISSUE TITLE
500 error when no results

### ISSUE THREAD

**Issue by bondjimbond** [bondjimbond/islandora_metadata_extras#35]
After #31 was merged, Islandora returns a 500 error when searching for a term that yields no results.

This only happens when the new setting is enabled. Search https://arcabc.ca for a nonsense string (e.g. adofijpaseoijf) and you get a 500 error.

Weirdly, with exactly the same Metadata Extras configuration in Vagrant, there's no problem. But my Vagrant modules aren't necessarily as up to date as production.

Can you help diagnose?

**Comment by mjordan** [comment]
What is appearing in your apache logs for these 500 errors? Anything in the Drupal watchdog?

**Comment by bondjimbond** [comment]
No logs at all.

The error occurs when this line is executed: https://github.com/mjordan/islandora_metadata_extras/blob/7.x/islandora_metadata_extras.module#L129

I'm trying to figure out a way to skip this line if there is nothing returned, but struggling.

**Comment by bondjimbond** [comment]
Also, these two lines seem superfluous: https://github.com/mjordan/islandora_metadata_extras/blob/7.x/islandora_metadata_extras.module#L127-L128

`facet_field_configured` is just a string; I cannot remember why I added an `explode()` function to it. There's no colon in the field name.
